-- liquibase formatted sql

--changeset shulga:1
CREATE TABLE Users
(
    id         bigint primary key,
    first_name TEXT,
    last_name  TEXT,
    phone      TEXT,
    email      TEXT,
    reg_date   TEXT,
    password   TEXT,
    role       INTEGER,
    username   TEXT

);

CREATE TABLE publication
(
    id      bigint generated by default as identity primary key,
    title   TEXT,
    text    TEXT,
    user_id bigint references Users (id) on delete cascade
);

CREATE TABLE photo
(
    id             bigint generated by default as identity primary key,
    file_size      bigint,
    media_type     varchar(255),
    photo          bytea,
    id_publication bigint REFERENCES publication (id) ON DELETE CASCADE
);

CREATE TABLE subscription
(
    id     bigint generated by default as identity primary key,
    friend TEXT,
    user_id bigint references Users (id) on delete cascade

);

alter table Users
    add column enabled boolean;
create sequence users_id_seq;
alter table Users
    alter column id set default nextval('users_id_seq');
alter sequence users_id_seq OWNED BY Users.id;

create table if not exists authorities
(
    username varchar
(
    255
) not null primary key,
    authority varchar
(
    32
)
    );
